services:
  nodejs:
    build:
      context: nodejs
    container_name: fullcycle_nodejs
    volumes:
      - ./nodejs:/app
      - /app/node_modules
    networks:
      - fullcycle-network
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:5.7
    container_name: fullcycle_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fullcycle
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
      - ./mysql-data:/var/lib/mysql
    networks:
      - fullcycle-network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '--silent']
      timeout: 20s
      retries: 5
    ports:
      - '3306:3306'

  nginx:
    build:
      context: nginx
    container_name: fullcycle_nginx
    ports:
      - 8080:80
    networks:
      - fullcycle-network
    depends_on:
      - nodejs

networks:
  fullcycle-network:
    driver: bridge
