services:
  nodejs:
    build:
      context: nodejs
    container_name: fullcycle_nodejs
    ports:
      - 8080:8080
    networks:
      - fullcycle-network
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: fullcycle_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fullcycle
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - fullcycle-network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10

networks:
  fullcycle-network:
    driver: bridge
